services:
  - type: web
    name: ankitchaudhary-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_URL
        value: https://ankitchaudhary.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: fate4nkit@gmail.com
      - key: EMAIL_FROM_NAME
        value: Chaudhary & Sons
